name: Deploy Node Application

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t asumancw/reactjs-app --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_SERVER_BASE_URL=${{ secrets.REACT_APP_SERVER_BASE_URL }}  .
      - name: message
        run: echo "docker check..................."
      - name: directory list
        run: docker images
      - name: docker push control
        run: docker pull asumancw/blue 
      - name: Publish Image to docker hub
        run: docker push asumancw/reactjs-app:latest 
      
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull asumancw/reactjs-app:latest 
      - name: Delete old container
        run: docker rm -f reactjs-app-container  
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactjs-app-container asumancw/reactjs-app
